Lesson2 task4
jguncheg/KotlinSprint pull request #13
Opened 2023-09-16 14:37 UTC by jguncheg

2023-09-16 21:03 UTC, ievetrov requested changes

2023-09-16 21:03 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +   val crystalBuff = crystal*20/100
окей. но напомню что арифметические знаки обосабливаются пробелами)

а еще, чтобы сделать программу поддерживаемой и гибкой - лучше проценты тоже вынести в переменную. потому что в случае изменения значения, придется менять в разных местах кода

2023-09-16 21:23 UTC, jguncheg commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +   val crystalBuff = crystal*20/100
пофиксил

2023-09-17 10:57 UTC, ievetrov approved these changes
Теперь отлично)

2023-09-17 19:33 UTC, merged